### ISSUE TITLE
ConvSpeechModel does not runs

### ISSUE THREAD

**Issue by ilanzylberberg** [douglas125/SpeechCmdRecognition#8]
Hi Doglas, 

Nice work in this project. 
but I am trying to run it in all models that was published and in ConvSpeechModel I am getting this error:

Traceback (most recent call last):
  File "C:/Users/.../SpeechCmdRecognition-master/run.py", line 126, in <module>
    model = SpeechModels.ConvSpeechModel(nCategs, samplingrate = sr, inputLength= None)
  File "C:\Users\...\SpeechCmdRecognition-master\SpeechModels.py", line 53, in ConvSpeechModel
    p3 = L.Dense(64, activation='relu')(p3)
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 897, in __call__
    self._maybe_build(inputs)
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1154, in build
    raise ValueError('The last dimension of the inputs to `Dense` '
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

Can you assist me with this issue?

**Comment by douglas125** [comment]
Sure

My first guess would be that you are using `inputLength=None` - you need a fixed input length for this model to work.

If that is the case, try `inputLength=16000` or whatever length you need.

Would you mind sharing some code to reproduce the issue?

**Comment by ilanzylberberg** [comment]
yes in the first try I was using as we can see in the traceback from my previous comment:
model = SpeechModels.ConvSpeechModel(nCategs, samplingrate = sr, inputLength= None)

the I tried as you told with inputLength= 16000:
I am running Speech_Recog_Demo.ipynb in Colab or local just changing the model as:
model = SpeechModels.ConvSpeechModel(nCategs, samplingrate = sr, inputLength= 16000)

and in the SpeechModel:
def ConvSpeechModel(nCategories, samplingrate=16000, inputLength=16000):

and the traceback:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\helpers\pydev\pydevd.py", line 2060, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\helpers\pydev\pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\helpers\pydev\pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\helpers\pydev\pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/ilanz/OneDrive/Desktop/Final_Project/attention/A neural attention model for speech command recognition/SpeechCmdRecognition-master/run.py", line 127, in <module>
    model = SpeechModels.ConvSpeechModel(nCategs, samplingrate = sr, **inputLength= 16000**)
  File "C:\Users\ilanz\OneDrive\Desktop\Final_Project\attention\A neural attention model for speech command recognition\SpeechCmdRecognition-master\SpeechModels.py", line 53, in ConvSpeechModel
    p3 = L.Dense(64, activation='relu')(p3)
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 897, in __call__
    self._maybe_build(inputs)
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\layers\core.py", line 1154, in build
    raise ValueError('The last dimension of the inputs to `Dense` '
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

If I comment the flatten line in the model I don't get this error.
    # p3 = L.Flatten()(p3)
    p3 = L.Dense(64, activation='relu')(p3)
    p3 = L.Dense(32, activation='relu')(p3)

**Comment by douglas125** [comment]
Ok, nice then!

It's hard to review everything everytime tensorflow changes version.

Feel free to reopen if needed.

**Comment by ilanzylberberg** [comment]
If I run with flatten in comment I got this:
C:\Users\ilanz\AppData\Local\Programs\Python\Python36\python.exe "C:/Users/ilanz/attention/A neural attention model for speech command recognition/SpeechCmdRecognition-master/run.py"
2020-09-19 22:57:11.995460: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-19 22:57:11.995664: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Google Speech commands dataset version 2 already exists. Skipping download.
Converting test set WAVs to numpy files
0it [00:00, ?it/s]
Converting training set WAVs to numpy files
0it [00:00, ?it/s]
Done preparing Google Speech commands dataset version 2
dict_keys(['train', 'test', 'val', 'testREAL'])
dict_keys(['files', 'labels'])
84849
12
2020-09-19 22:57:15.362553: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-09-19 22:57:15.362755: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-19 22:57:15.365914: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: LAPTOP-DOJPO11P
2020-09-19 22:57:15.366158: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: LAPTOP-DOJPO11P
2020-09-19 22:57:15.366418: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-09-19 22:57:15.372223: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x25294f70ec0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-19 22:57:15.372545: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
mel_stft (Melspectrogram)    (None, 80, 125, 1)        1091664   
_________________________________________________________________
normalization2d (Normalizati (None, 80, 125, 1)        0         
=================================================================
Total params: 1,091,664
Trainable params: 1,091,664
Non-trainable params: 0
_________________________________________________________________
(32, 80, 125, 1)
Model: "ConvSpeechModel"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 16000)]           0         
_________________________________________________________________
reshape (Reshape)            (None, 1, None)           0         
_________________________________________________________________
mel_stft (Melspectrogram)    (None, 80, None, 1)       1091664   
_________________________________________________________________
normalization2d_1 (Normaliza (None, 80, None, 1)       0         
_________________________________________________________________
permute (Permute)            (None, None, 80, 1)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, None, 80, 20)      120       
_________________________________________________________________
batch_normalization (BatchNo (None, None, 80, 20)      80        
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, None, 80, 20)      0         
_________________________________________________________________
dropout (Dropout)            (None, None, 80, 20)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, None, 80, 40)      7240      
_________________________________________________________________
batch_normalization_1 (Batch (None, None, 80, 40)      160       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, None, 40, 40)      0         
_________________________________________________________________
dropout_1 (Dropout)          (None, None, 40, 40)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, None, 40, 80)      28880     
_________________________________________________________________
batch_normalization_2 (Batch (None, None, 40, 80)      320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, None, 20, 80)      0         
_________________________________________________________________
dense (Dense)                (None, None, 20, 64)      5184      
_________________________________________________________________
dense_1 (Dense)              (None, None, 20, 32)      2080      
_________________________________________________________________
dense_2 (Dense)              (None, None, 20, 12)      396       
=================================================================
Total params: 1,136,124
Trainable params: 1,135,844
Non-trainable params: 280
_________________________________________________________________
Model: "ConvSpeechModel"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 16000)]           0         
_________________________________________________________________
reshape (Reshape)            (None, 1, None)           0         
_________________________________________________________________
mel_stft (Melspectrogram)    (None, 80, None, 1)       1091664   
_________________________________________________________________
normalization2d_1 (Normaliza (None, 80, None, 1)       0         
_________________________________________________________________
permute (Permute)            (None, None, 80, 1)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, None, 80, 20)      120       
_________________________________________________________________
batch_normalization (BatchNo (None, None, 80, 20)      80        
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, None, 80, 20)      0         
_________________________________________________________________
dropout (Dropout)            (None, None, 80, 20)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, None, 80, 40)      7240      
_________________________________________________________________
batch_normalization_1 (Batch (None, None, 80, 40)      160       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, None, 40, 40)      0         
_________________________________________________________________
dropout_1 (Dropout)          (None, None, 40, 40)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, None, 40, 80)      28880     
_________________________________________________________________
batch_normalization_2 (Batch (None, None, 40, 80)      320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, None, 20, 80)      0         
_________________________________________________________________
dense (Dense)                (None, None, 20, 64)      5184      
_________________________________________________________________
dense_1 (Dense)              (None, None, 20, 32)      2080      
_________________________________________________________________
dense_2 (Dense)              (None, None, 20, 12)      396       
=================================================================
Total params: 1,136,124
Trainable params: 1,135,844
Non-trainable params: 280
_________________________________________________________________
Changing learning rate to 0.001
Epoch 1/50
Traceback (most recent call last):
  File "C:/Users/ilanz/OneDrive/Desktop/Final_Project/attention/A neural attention model for speech command recognition/SpeechCmdRecognition-master/run.py", line 164, in <module>
    callbacks=[earlystopper, checkpointer, lrate])
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\def_function.py", line 644, in _call
    return self._stateless_fn(*args, **kwds)
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 1665, in _filtered_call
    self.captured_inputs)
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 1746, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\function.py", line 598, in call
    ctx=ctx)
  File "C:\Users\ilanz\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [32,1] vs. [32,15,20]
	 [[node Equal (defined at /Users/ilanz/attention/A neural attention model for speech command recognition/SpeechCmdRecognition-master/run.py:164) ]] [Op:__inference_train_function_2917]

Function call stack:
train_function

2020-09-19 22:57:18.258478: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]

Process finished with exit code 1
